name             'sch-timberslide'
maintainer       'David F. Severski'
maintainer_email 'davidski@deadheaven.com'
license          'MIT'
description      'Installs/Configures Timberslide'
long_description 'Installs/Configures Timberslide'

version          '0.1.0'
depends 'git_user'
depends 'python'
depends 'postgresql'
depends 'chef-sugar'
#depends 'aws-rds'
#depends 'aws-sdk'